spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id:  Iv1.bd63057cd157ca15
            client-secret: 0c2d360b80f48550e1ef2e88e0d85ce9a7b38e88
  cassandra:
    keyspace-name: main
    username: RNsSTjGxEzBcnaEyJTGcCPcq
    password: 4j4zw0zb2YslTUMRbO+xBlr+k+aN3KML9,Zny0ZH5MoOYP47WMBg0Ql-Q2Sj7+0ATBFFneRqjX6j4Q2adDCBYzsNb87qGN8qWx,9Bz+oSS6OWLeUEOgrKo31ikOOHgSF
    schema-action: create_if_not_exists
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s
  main:
    allow-circular-references: true

datastax.astra:
  secure-connect-bundle: secure-connect.zip

astra.db:
  id: c8dafd80-d07d-4232-a4de-214f651ee277-1
  region: asia-south1
  keyspace: main
  application.token: AstraCS:RNsSTjGxEzBcnaEyJTGcCPcq:c366925340676fb03b49e89ac11bd20b8a4470884d64ebff8e07487cf4d27300
